apiVersion: constraints.gatekeeper.sh/v1beta1
kind: XAppImageSafety
metadata:
  name: imagemustfromtrustedsource
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]  
    excludedNamespaces: ["kube-system","weave","gatekeeper-system","ricplt","ricinfra","default"]

