apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: xappimagesafety
spec:
  crd:
    spec:
      names:
        kind: XAppImageSafety
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
        #   properties:
        #     labels:
        #       type: array
        #       items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package xappimagesafety

        violation [{"msg": msg }] {    
          image := input.review.object.spec.containers[_].image
          not startswith(image, "nexus3.o-ran-sc.org:10002/o-ran-sc/")  
          msg := sprintf("image '%v' comes from untrusted registry", [image])
        }
